### ISSUE TITLE
Set guidelines for contributors using CONTRIBUTING.md file

### ISSUE THREAD

**Issue by teles** [IuryAlves/TryPython#5]
The contributing section on your readme file could be replaced by a contributing.md file, take a look: https://help.github.com/articles/setting-guidelines-for-repository-contributors

**Comment by IuryAlves** [comment]
Boa!

**Comment by IuryAlves** [comment]
This [commit](https://github.com/IuryAlves/TryPython/commit/2713d4b3dff9534b70082f1905f1e7aa2d258013) solves the iissue.
